[package]
name = "atom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic-wait = "1.1.0"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.139"
